server:
  port: ${LIBRARY_SERVICE_PORT:8082}

spring:
  application:
    name: library-service
  datasource:
    url: ${LIBRARY_DB_URL:jdbc:postgresql://localhost:5433/library_db}
    username: ${LIBRARY_DB_USERNAME:postgres}
    password: ${LIBRARY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/game-cellar}

game-service:
  url: ${GAME_SERVICE_URL:http://localhost:8081}
  connect-timeout: ${GAME_SERVICE_CONNECT_TIMEOUT:2000}
  read-timeout: ${GAME_SERVICE_READ_TIMEOUT:5000}

logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%X{requestId:-........}]){magenta} %clr([%-15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"