-- Baseline schema for library_db. Captures the live state of the database as of 2026-05-07
-- when versioned migrations were re-introduced. Subsequent schema changes go in V2, V3, etc.
--
-- Notes:
-- - On a fresh empty database Flyway runs this file as V1.
-- - On the existing dev/prod database Flyway baseline-on-migrate stamps V1 as already-applied
--   without re-executing it, since the tables already exist.
-- - This file mirrors the current live state. The UNIQUE (user_id, igdb_game_id) constraint
--   that the UserGame entity declares but the live DB lacks is added in V2 — keeping V1
--   faithful to the actual baseline keeps the "what was vs what is" diff clear in history.

CREATE TABLE user_games (
    id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    igdb_game_id INTEGER NOT NULL,
    game_name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    rating INTEGER,
    platform VARCHAR(255) NOT NULL,
    date_added TIMESTAMP(6),
    last_played TIMESTAMP(6),
    playtime INTEGER,
    background_image VARCHAR(255),
    genres VARCHAR(255),
    themes TEXT,
    tags TEXT,
    notes VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT user_games_pkey PRIMARY KEY (id),
    CONSTRAINT user_games_status_check CHECK (status IN ('PLAYING', 'BACKLOG', 'COMPLETED', 'DROPPED', 'WISHLIST', 'DUSTY'))
);

ALTER TABLE user_games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE user_platforms (
    id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    platform_name VARCHAR(255) NOT NULL,
    is_primary BOOLEAN,
    CONSTRAINT user_platforms_pkey PRIMARY KEY (id),
    CONSTRAINT ukrp1xrruxsaddq2bq4juljmlpk UNIQUE (user_id, platform_name)
);

ALTER TABLE user_platforms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_platforms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
