-- Optional cold-start signal collected during onboarding (and editable from the user's
-- profile) that blends into the recommendation pipeline alongside actual ratings. Mirrors
-- the user_platforms shape: same (user_id, name) uniqueness invariant, same VARCHAR
-- user_id stand-in for the Keycloak UUID (no FK across services).

CREATE TABLE user_genre_preferences (
    id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    genre_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_genre_preferences_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_genre_preference UNIQUE (user_id, genre_name)
);

ALTER TABLE user_genre_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_genre_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX idx_user_genre_preferences_user_id ON user_genre_preferences (user_id);
