-- Optional cold-start signal collected from the Profile / Preferences page that blends into
-- the recommendation pipeline alongside actual ratings. Mirrors user_genre_preferences exactly
-- (same uniqueness invariant, same VARCHAR(255) user_id Keycloak UUID stand-in, no FK across
-- services). Companion to user_genre_preferences for the tags dimension of the multi-dim
-- profile so users can declare preferred gameplay styles, atmospheres, and settings beyond
-- the broader genre taxonomy.

CREATE TABLE user_tag_preferences (
    id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    tag_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_tag_preferences_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_tag_preference UNIQUE (user_id, tag_name)
);

ALTER TABLE user_tag_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_tag_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX idx_user_tag_preferences_user_id ON user_tag_preferences (user_id);
