-- Third declared-preference dimension feeding the recommendation blend alongside genres and
-- tags. Users pick preferred release-era decade buckets in Profile / Preferences; the
-- recommendation service classifies each candidate game's first-release-date into the same
-- buckets and applies a soft scoring boost when there is a match. Schema mirrors
-- user_genre_preferences and user_tag_preferences exactly: same uniqueness invariant, same
-- VARCHAR(255) user_id Keycloak UUID stand-in, no FK across services.

CREATE TABLE user_release_year_preferences (
    id BIGINT NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    bucket_label VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_release_year_preferences_pkey PRIMARY KEY (id),
    CONSTRAINT uk_user_release_year_preference UNIQUE (user_id, bucket_label)
);

ALTER TABLE user_release_year_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_release_year_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX idx_user_release_year_preferences_user_id ON user_release_year_preferences (user_id);
